name: Something else
description: "For when you're unsure, or for general questions, like the meaning of life. (spoiler: it's time² ÷ (money - attitude) + √good^evil ÷ (idea + random))"
assignees: ["Commenter25"]

body:
  - type: markdown
    attributes:
      value: "Thank you for making an issue! Please be sure to add a short and simple title above, with no tagging like [QUESTION]."

  - type: textarea
    id: whathappened
    attributes:
      label: What would you like to say?
      placeholder: Say what you want to say!
    validations:
      required: true
